spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5433/deliveryflow_notifications
    username: deliveryflow
    password: deliveryflow
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
