image:
  repository: ghcr.io/arkadiuszrybka/delivery-flow-tracking-service
  tag: "8f2a26cfd36b3d20c8b22723870622bacb489581"
  pullPolicy: IfNotPresent

replicaCount: 2

containerPort: 8082

service:
  port: 8082

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

dbCredentialsSecret: deliveryflow-db-credentials

infra:
  postgresHost: ""
  postgresPort: 5432
  postgresDb: deliveryflow_tracking
