image:
  repository: 404842057803.dkr.ecr.eu-central-1.amazonaws.com/deliveryflow-tracking-service
  tag: "5fc7e3bea32fb4df5e966468b9ee43dbc4d5dc55"
  pullPolicy: IfNotPresent

replicaCount: 2

containerPort: 8082

service:
  port: 8082

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

dbCredentialsSecret: deliveryflow-db-credentials

infra:
  postgresHost: ""
  postgresPort: 5432
  postgresDb: deliveryflow_tracking
