image:
  repository: ghcr.io/arkadiuszrybka/delivery-flow-tracking-service
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

containerPort: 8082

service:
  port: 8082

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

dbCredentialsSecret: deliveryflow-db-credentials

infra:
  postgresHost: ""
  postgresPort: 5432
  postgresDb: deliveryflow_tracking
