apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.infra.postgresHost }}:{{ .Values.infra.postgresPort }}/{{ .Values.infra.postgresDb }}"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.infra.kafkaBootstrapServers }}"
{{- if .Values.infra.kafkaSaslIam }}
  SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL: "SASL_SSL"
  SPRING_KAFKA_PROPERTIES_SASL_MECHANISM: "AWS_MSK_IAM"
  SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG: "software.amazon.msk.auth.iam.IAMLoginModule required;"
  SPRING_KAFKA_PROPERTIES_SASL_CLIENT_CALLBACK_HANDLER_CLASS: "software.amazon.msk.auth.iam.IAMClientCallbackHandler"
{{- end }}
