spring:
  application:
    name: api-gateway

  web:
    resources:
      add-mappings: false

server:
  port: 8080

jwt:
  public-key: classpath:certs/public.pem

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 0.0
