apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  ORDER_SERVICE_URI: "{{ .Values.routes.orderServiceUri }}"
  TRACKING_SERVICE_URI: "{{ .Values.routes.trackingServiceUri }}"
  JWT_PUBLIC_KEY_PATH: "file:/etc/secrets/jwt/public.pem"
