{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-gateway-secrets-sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.appSecret }}
  data:
    - secretKey: public.pem
      remoteRef:
        key: deliveryflow/jwt/keypair
        property: public_key
{{- end }}
