image:
  repository: ghcr.io/arkadiuszrybka/delivery-flow-notification-service
  tag: "256a5a74846cb52a80689f68791fad463ea1621a"
  pullPolicy: IfNotPresent

replicaCount: 1

containerPort: 8083

service:
  port: 8083

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

dbCredentialsSecret: deliveryflow-db-credentials

infra:
  postgresHost: ""
  postgresPort: 5432
  postgresDb: deliveryflow_notifications
  kafkaBootstrapServers: ""
