image:
  repository: 404842057803.dkr.ecr.eu-central-1.amazonaws.com/deliveryflow-notification-service
  tag: "e3c43a180a7a9e65d419b60704f40db280b65ae7"
  pullPolicy: IfNotPresent

replicaCount: 1

containerPort: 8083

service:
  port: 8083

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

dbCredentialsSecret: deliveryflow-db-credentials

infra:
  postgresHost: ""
  postgresPort: 5432
  postgresDb: deliveryflow_notifications
  kafkaBootstrapServers: ""
  kafkaSaslIam: false
