image:
  repository: 404842057803.dkr.ecr.eu-central-1.amazonaws.com/deliveryflow-notification-service
  tag: "623438bd30bbeffcd68de428dcd123dd614f3718"
  pullPolicy: IfNotPresent

replicaCount: 1

containerPort: 8083

service:
  port: 8083

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

dbCredentialsSecret: deliveryflow-db-credentials

infra:
  postgresHost: ""
  postgresPort: 5432
  postgresDb: deliveryflow_notifications
  kafkaBootstrapServers: ""
