apiVersion: v1
kind: ConfigMap
metadata:
  name: tracking-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.infra.postgresHost }}:{{ .Values.infra.postgresPort }}/{{ .Values.infra.postgresDb }}"
