image:
  repository: 404842057803.dkr.ecr.eu-central-1.amazonaws.com/deliveryflow-order-service
  tag: "e3c43a180a7a9e65d419b60704f40db280b65ae7"
  pullPolicy: IfNotPresent

replicaCount: 1

containerPort: 8081

service:
  port: 8081

resources:
  requests:
    cpu: 200m
    memory: 384Mi
  limits:
    memory: 768Mi

dbCredentialsSecret: deliveryflow-db-credentials
appSecret: order-service-secrets

externalSecrets:
  enabled: false

infra:
  postgresHost: ""
  postgresPort: 5432
  postgresDb: deliveryflow_orders
  redisHost: ""
  redisPort: 6379
  kafkaBootstrapServers: ""
  kafkaSaslIam: false
  trackingServiceUri: http://tracking-service:8082
