spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5433/deliveryflow_orders
    username: deliveryflow
    password: deliveryflow
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      acks: all
      properties:
        spring.json.add.type.headers: false

server:
  port: 8081

clients:
  tracking-service:
    base-url: http://localhost:8082
    connect-timeout: 2s
    read-timeout: 3s

resilience4j:
  circuitbreaker:
    instances:
      trackingService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 15
        minimum-number-of-calls: 15
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      trackingService:
        max-attempts: 3
        wait-duration: 500ms

jwt:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
  access-expiration: 900
  refresh-expiration: 2592000

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 0.0
