image:
  repository: 404842057803.dkr.ecr.eu-central-1.amazonaws.com/deliveryflow-api-gateway
  tag: "e3c43a180a7a9e65d419b60704f40db280b65ae7"
  pullPolicy: IfNotPresent

replicaCount: 1

containerPort: 8080
managementPort: 8090

service:
  type: NodePort
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

appSecret: api-gateway-secrets

externalSecrets:
  enabled: false

routes:
  orderServiceUri: http://order-service:8081
  trackingServiceUri: http://tracking-service:8082
