{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: order-service-secrets-sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.appSecret }}
  data:
    - secretKey: stripe-secret-key
      remoteRef:
        key: deliveryflow/stripe/keys
        property: secret_key
    - secretKey: stripe-webhook-secret
      remoteRef:
        key: deliveryflow/stripe/keys
        property: webhook_secret
    - secretKey: private.pem
      remoteRef:
        key: deliveryflow/jwt/keypair
        property: private_key
    - secretKey: public.pem
      remoteRef:
        key: deliveryflow/jwt/keypair
        property: public_key
{{- end }}
